name: Commit Message Checker
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-commit-message:
    uses: IsyFact/isy-github-actions-templates/.github/workflows/commit_message_checker_template.yml@v1.5.0