name: Bugfix Workflow

on:
  push:
    branches:
      - fix/*
  workflow_dispatch:
jobs:
  MavenBuild:
    uses: IsyFact/isyfact-standards/.github/workflows/maven_build_template.yml@master
    with:
      jdk-version: 21
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}